export type SpellLevel = "Cantrip" | "1st" | "2nd" | "3rd" | "4th" | "5th" | "6th" | "7th" | "8th" | "9th"

export type SpellSchool = string //TODO: list schools of magic

export type Spell = {
    name: string
    level: SpellLevel
    school: SpellSchool
    castTime: string
    range: string
    areaOfEffect?: string
    components: string
    materials?: string
    duration: string
    description: string
    higherLevel?: string
    concentration?: boolean
    ritual?: boolean
    alwaysPrepared?: boolean
}

export const MAX_PREPARED = 11;

export const spells: Spell[] = [{
    name: "Guidance",
    level: "Cantrip",
    school: "Divination",
    castTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "1 Minute",
    concentration: true,
    description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.",
}, {
    name: "Minor Illusion",
    level: "Cantrip",
    school: "Illusion",
    castTime: "1 Action",
    range: "30 ft",
    components: "S, M",
    materials: "A bit of fleece",
    duration: "1 Minute",
    description: "You create a sound or an image of an object within range that lasts for the duration.The illusion also ends if you dismiss it as an action or cast this spell again.\n\nIf you create a sound, its volume can range from a whisper to a scream.It can be your voice, someone else 's voice, a lion's roar, a beating of drums, or any other sound you choose.The sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends.\n\nIf you create an image of an object--such as a chair, muddy footprints, or a small chest--it must be no larger than a 5 - foot cube.The image can't create sound, light, smell, or any other sensory effect. Physical interaction with the image reveals it to be an illusion, because things can pass through it.\n\nIf a creature uses its action to examine the sound or image, the creature can determine that it is an illusion with a successful Intelligence(Investigation) check against your spell save DC.If a creature discerns the illusion for what it is, the illusion becomes faint to the creature.",
}, {
    name: "Prestidigitation",
    level: "Cantrip",
    school: "Transmutation",
    castTime: "1 Action",
    range: "10 ft",
    components: "V, S",
    duration: "Up to 1 hour",
    description: "This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range:\n\nYou create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor.\n\nYou instantaneously light or snuff out a candle, a torch, or a small campfire.\n\nYou instantaneously clean or soil an object no larger than 1 cubic foot.\n\nYou chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour.\n\nYou make a color, a small mark, or a symbol appear on an object or a surface for 1 hour.\n\nYou create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn.\n\nIf you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.",
}, {
    name: "Ray of Frost",
    level: "Cantrip",
    school: "Evocation",
    castTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    description: "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.",
    higherLevel: "The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8)."
}, {
    name: "Shillelagh",
    level: "Cantrip",
    school: "Transmutation",
    castTime: "1 Bonus Action",
    range: "Touch",
    components: "V, S, M",
    materials: "Mistletoe, a shamrock leaf, and a club or quarterstaff",
    duration: "1 minute",
    description: "The wood of a club or quarterstaff you are holding is imbued with nature’s power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon’s damage die becomes a d8. The weapon also becomes magical, if it isn’t already. The spell ends if you cast it again or if you let go of the weapon.",
}, {
    name: "Toll the Dead",
    level: "Cantrip",
    school: "Evocation",
    castTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    description: "You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take 1d8 necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage.",
    higherLevel: "The spell’s damage increases by one die when you reach 5th level (2d8 or 2d12), 11th level (3d8 or 3d12), and 17th level (4d8 or 4d12)."
}, {
    name: "Comprehend Languages",
    level: "1st",
    school: "Divination",
    ritual: true,
    castTime: "1 Action",
    range: "Self",
    components: "V, S, M",
    materials: "A pinch of soot and salt",
    duration: "1 hour",
    description: "For the duration, you understand the literal meaning of any spoken language that you hear.You also understand any written language that you see, but you must be touching the surface on which the words are written.It takes about 1 minute to read one page of text.\n\nThis spell doesn’t decode secret messages in a text or a glyph, such as an arcane sigil, that isn’t part of a written language.",
}, {
    name: "Detect Magic",
    level: "1st",
    school: "Divination",
    ritual: true,
    castTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "Up to 10 minutes",
    concentration: true,
    description: "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any.\n\nThe spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.",
}, {
    name: "Faerie Fire",
    level: "1st",
    school: "Evocation",
    castTime: "1 Action",
    range: "60 ft",
    areaOfEffect: "20 ft cube",
    components: "V",
    duration: "Up to 1 minute",
    concentration: true,
    description: "Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius.\n\nAny attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can’t benefit from being invisible.",
    alwaysPrepared: true,
}, {
    name: "Find Familiar",
    level: "1st",
    school: "Conjuration",
    ritual: true,
    castTime: "1 hour",
    range: "10 ft",
    components: "V, S, M",
    materials: "10 gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier",
    duration: "Instant",
    description: "You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog (toad), hawk, lizard, octopus, owl, poisonous snake, fish (quipper), rat, raven, sea horse, spider, or weasel. Appearing in an unoccupied space within range, the familiar has the statistics of the chosen form, though it is a celestial, fey, or fiend (your choice) instead of a beast.\n\nYour familiar acts independently of you, but it always obeys your commands.In combat, it rolls its own initiative and acts on its own turn.A familiar can’t attack, but it can take other actions as normal.\n\nWhen the familiar drops to 0 hit points, it disappears, leaving behind no physical form.It reappears after you cast this spell again\n\nWhile your familiar is within 100 feet of you, you can communicate with it telepathically.Additionally, as an action, you can see through your familiar’s eyes and hear what it hears until the start of your next turn, gaining the benefits of any special senses that the familiar has.During this time, you are deaf and blind with regard to your own senses.\n\nAs an action, you can temporarily dismiss your familiar.It disappears into a pocket dimension where it awaits your summons.Alternatively, you can dismiss it forever.As an action while it is temporarily dismissed, you can cause it to reappear in any unoccupied space within 30 feet of you.\n\nYou can’t have more than one familiar at a time.If you cast this spell while you already have a familiar, you instead cause it to adopt a new form.Choose one of the forms from the above list.Your familiar transforms into the chosen creature.\n\nFinally, when you cast a spell with a range of touch, your familiar can deliver the spell as if it had cast the spell.Your familiar must be within 100 feet of you, and it must use its reaction to deliver the spell when you cast it.If the spell requires an attack roll, you use your attack modifier for the roll.",
}, {
    name: "Sleep",
    level: "1st",
    school: "Enchantment",
    castTime: "1 action",
    range: "90 ft",
    areaOfEffect: "20 ft radius",
    components: "V, S, M",
    materials: "A pinch of fine sand, rose petals, or a cricket",
    duration: "1 minute",
    description: "This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures). Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake. Subtract each creature’s hit points from the total before moving on to the creature with the next lowest hit points. A creature’s hit points must be equal to or less than the remaining total for that creature to be affected. Undead and creatures immune to being charmed aren’t affected by this spell.",
    higherLevel: "When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st."
}, {
    name: "Thunderwave",
    level: "1st",
    school: "Evocation",
    castTime: "1 action",
    range: "Self",
    areaOfEffect: "15 ft cube",
    components: "V, S",
    duration: "Instant",
    description: "A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn’t pushed. In addition, unsecured objects that are completely within the area of effect are automatically pushed 10 feet away from you by the spell’s effect, and the spell emits a thunderous boom audible out to 300 feet.",
    higherLevel: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st."
}, {
    name: "Magic Missile",
    level: "1st",
    school: "Evocation",
    castTime: "1 action",
    range: "120 ft",
    components: "V, S",
    duration: "Instant",
    description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.",
    higherLevel: "When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot above 1st."
}, {
    name: "Shield",
    level: "1st",
    school: "Abjuration",
    castTime: "1 reaction",
    range: "Self",
    components: "V, S",
    duration: "1 round",
    description: "An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.",
}, {
    name: "Mage Armor",
    level: "1st",
    school: "Abjuration",
    castTime: "1 action",
    range: "Touch",
    components: "V, S, M",
    materials: "A piece of cured leather",
    duration: "8 hours",
    description: "You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends. The target’s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.",
}, {
    name: "Unseen Servant",
    level: "1st",
    school: "Conjuration",
    ritual: true,
    castTime: "1 action",
    range: "60 ft",
    components: "V, S, M",
    materials: "A piece of string and a bit of wood",
    duration: "1 hour",
    description: "This spell creates an invisible, mindless, shapeless force that performs simple tasks at your command until the spell ends. The servant springs into existence in an unoccupied space on the ground within range. It has AC 10, 1 hit point, and a Strength of 2, and it can’t attack. If it drops to 0 hit points, the spell ends.\n\nOnce on each of your turns as a bonus action, you can mentally command the servant to move up to 15 feet and interact with an object.The servant can perform simple tasks that a human servant could do, such as fetching things, cleaning, mending, folding clothes, lighting fires, serving food, and pouring wine.Once you give the command, the servant performs the task to the best of its ability until it completes the task, then waits for your next command.\n\nIf you command the servant to perform a task that would move it more than 60 feet away from you, the spell ends.",
}, {
    name: "Identify",
    level: "1st",
    school: "Divination",
    ritual: true,
    castTime: "1 minute",
    range: "Touch",
    components: "V, S, M",
    materials: "A pearl worth at least 100gp and an owl feather",
    duration: "Instantaneous",
    description: "You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires Attunement to use, and how many Charges it has, if any. You learn whether any Spells are affecting the item and what they are. If the item was created by a spell, you learn which spell created it.\n\nIf you instead touch a creature throughout the casting, you learn what Spells, if any, are currently affecting it.",
}, {
    name: "Flaming Sphere",
    level: "2nd",
    school: "Conjuration",
    castTime: "1 action",
    range: "60 ft",
    components: "V, S, M",
    materials: "A bit of tallow, a pinch of brimstone, and a dusting of powdered iron",
    duration: "Up to 1 minute",
    concentration: true,
    description: "A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration. Any creature that ends its turn within 5 feet of the sphere must make a Dexterity saving throw. The creature takes 2d6 fire damage on a failed save, or half as much damage on a successful one. As a bonus action, you can move the sphere up to 30 feet. If you ram the sphere into a creature, that creature must make the saving throw against the sphere’s damage, and the sphere stops moving this turn. When you move the sphere, you can direct it over barriers up to 5 feet tall and jump it across pits up to 10 feet wide. The sphere ignites flammable objects not being worn or carried, and it sheds bright light in a 20-foot radius and dim light for an additional 20 feet.",
    higherLevel: "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot level above 2nd."
}, {
    name: "Misty Step",
    level: "2nd",
    school: "Conjuration",
    castTime: "1 bonus action",
    range: "Self",
    components: "V",
    duration: "Instant",
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.",
}, {
    name: "Web",
    level: "2nd",
    school: "Conjuration",
    castTime: "1 action",
    range: "60 ft",
    components: "V, S, M",
    materials: "A bit of spiderweb",
    duration: "Up to 1 hour",
    concentration: true,
    description: "You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot cube from that point for the duration. The webs are difficult terrain and lightly obscure their area.\n\nIf the webs aren’t anchored between two solid masses(such as walls or trees) or layered across a floor, wall, or ceiling, the conjured web collapses on itself, and the spell ends at the start of your next turn.Webs layered over a flat surface have a depth of 5 feet.\n\nEach creature that starts its turn in the webs or that enters them during its turn must make a Dexterity saving throw.On a failed save, the creature is restrained as long as it remains in the webs or until it breaks free.\n\nA creature restrained by the webs can use its action to make a Strength check against your spell save DC.If it succeeds, it is no longer restrained.\n\nThe webs are flammable.Any 5-foot cube of webs exposed to fire burns away in 1 round, dealing 2d4 fire damage to any creature that starts its turn in the fire.",
}, {
    name: "Suggestion",
    level: "2nd",
    school: "Enchantment",
    castTime: "1 action",
    range: "30 ft",
    components: "V, M",
    materials: "A snake's tongue and either a bit of honeycomb or a drop of sweet oil",
    duration: "Up to 8 hour",
    concentration: true,
    description: "You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. Creatures that can’t be charmed are immune to this effect. The suggestion must be worded in such a manner as to make the course of action sound reasonable. Asking the creature to stab itself, throw itself onto a spear, immolate itself, or do some other obviously harmful act ends the spell.\n\nThe target must make a Wisdom saving throw.On a failed save, it pursues the course of action you described to the best of its ability.The suggested course of action can continue for the entire duration.If the suggested activity can be completed in a shorter time, the spell ends when the subject finishes what it was asked to do.\n\nYou can also specify conditions that will trigger a special activity during the duration.For example, you might suggest that a knight give her warhorse to the first beggar she meets.If the condition isn’t met before the spell expires, the activity isn’t performed.\n\nIf you or any of your companions damage the target, the spell ends.",
}, {
    name: "Counterspell",
    level: "3rd",
    school: "Abjuration",
    castTime: "1 reaction",
    range: "60 ft",
    components: "S",
    duration: "Instant",
    description: "You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell’s level. On a success, the creature’s spell fails and has no effect.\n\nAt Higher Levels.When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.",
}, {
    name: "Tiny Hut",
    level: "3rd",
    school: "Evocation",
    ritual: true,
    castTime: "1 minute",
    range: "Self",
    areaOfEffect: "10 ft radius hemisphere",
    components: "V, S, M",
    materials: "A small crystal bead",
    duration: "8 hours",
    description: "A 10-foot-radius immobile dome of force springs into existence around and above you and remains stationary for the duration. The spell ends if you leave its area.\n\nNine creatures of Medium size or smaller can fit inside the dome with you.The spell fails if its area includes a larger creature or more than nine creatures.Creatures and objects within the dome when you cast this spell can move through it freely.All other creatures and objects are barred from passing through it.Spells and other magical effects can’t extend through the dome or be cast through it.The atmosphere inside the space is comfortable and dry, regardless of the weather outside.\n\nUntil the spell ends, you can command the interior to become dimly lit or dark.The dome is opaque from the outside, of any color you choose, but it is transparent from the inside.",
}, {
    name: "Remove Curse",
    level: "3rd",
    school: "Abjuration",
    castTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instant",
    description: "At your touch, all curses affecting one creature or object end. If the object is a cursed magic item, its curse remains, but the spell breaks its owner’s attunement to the object so it can be removed or discarded.",
}, {
    name: "Slow",
    level: "3rd",
    school: "Transmutation",
    castTime: "1 action",
    range: "120 ft",
    components: "V, S, M",
    materials: "A drop of molasses",
    duration: "Up to 1 minute",
    concentration: true,
    description: "You alter time around up to six creatures of your choice in a 40-foot cube within range. Each target must succeed on a Wisdom saving throw or be affected by this spell for the duration.\n\nAn affected target’s speed is halved, it takes a −2 penalty to AC and Dexterity saving throws, and it can’t use reactions.On its turn, it can use either an action or a bonus action, not both.Regardless of the creature’s abilities or magic items, it can’t make more than one melee or ranged attack during its turn.\n\nIf the creature attempts to cast a spell with a casting time of 1 action, roll a d20.On an 11 or higher, the spell doesn’t take effect until the creature’s next turn, and the creature must use its action on that turn to complete the spell.If it can’t, the spell is wasted.\n\nA creature affected by this spell makes another Wisdom saving throw at the end of its turn.On a successful save, the effect ends for it.",
}, {
    name: "Sending",
    level: "3rd",
    school: "Evocation",
    castTime: "1 action",
    range: "Unlimited",
    components: "V, S, M",
    materials: "A short piece of fine copper wire",
    duration: "1 round",
    description: "You send a short message of twenty-five words or less to a creature with which you are familiar. The creature hears the message in its mind, recognizes you as the sender if it knows you, and can answer in a like manner immediately. The spell enables creatures with Intelligence scores of at least 1 to understand the meaning of your message.\n\nYou can send the message across any distance and even to other planes of existence, but if the target is on a different plane than you, there is a 5 percent chance that the message doesn’t arrive.",
}, {
    name: "Polymorph",
    level: "4th",
    school: "Transmutation",
    castTime: "1 action",
    concentration: true,
    range: "60 ft",
    components: "V, S, M",
    materials: "a caterpiller cocoon",
    duration: "1 hour",
    description: "This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. A shapechanger automatically succeeds on this saving throw.\n\nThe transformation lasts for the duration, or until the target drops to 0 hit points or dies.The new form can be any beast whose challenge rating is equal to or less than the target's (or the target's level, if it doesn't have a challenge rating). The target's game statistics, including mental ability scores, are replaced by the statistics of the chosen beast.It retains its alignment and personality.\n\nThe target assumes the hit points of its new form.When it reverts to its normal form, the creature returns to the number of hit points it had before it transformed.If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form.As long as the excess damage doesn't reduce the creature's normal form to 0 hit points, it isn't knocked unconscious.\n\nThe creature is limited in the actions it can perform by the nature of its new form, and it can't speak, cast spells, or take any other action that requires hands or speech.\n\nThe target's gear melds into the new form. The creature can't activate, use, wield, or otherwise benefit from any of its equipment.",
}, {
    name: "Otiluke's Resilient Sphere",
    level: "4th",
    school: "Evocation",
    castTime: "1 action",
    concentration: true,
    range: "30 ft",
    components: "V, S, M",
    materials: "A hemispherical piece of clear crystal and matching hemispherical piece of gum arabic",
    duration: "1 minute",
    description: "A sphere of shimmering force encloses a creature or object of Large size or smaller within range. An unwilling creature must make a Dexterity saving throw. On a failed save, the creature is enclosed for the duration.\n\nNothing - not physical objects, energy, or other spell effects - can pass through the barrier, in or out, though a creature in the sphere can breathe there.The sphere is immune to all damage, and a creature or object inside can't be damaged by attacks or effects originating from outside, nor can a creature inside the sphere damage anything outside it.\n\nThe sphere is weightless and just large enough to contain the creature or object inside.An enclosed creature can use its action to push against the sphere's walls and thus roll the sphere at up to half the creature's speed.Similarly, the globe can be picked up and moved by other creatures.\n\nA disintegrate spell targeting the globe destroys it without harming anything inside it.",
}];
